default_config:

logger:
  default: info
  logs:
    custom_components.filter_calendar: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:
calendar:
  - platform: filter_calendar
    name: Race Weekends
    tracking: family
    filter: "Andrew - Race Weekend"
